kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.name}}
  namespace: {{.namespace}}
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    #volume.beta.kubernetes.io/storage-class: "{{storageclass.name}}"
spec:
  accessModes:
    - ReadWriteMany
    #- ReadWriteOnce
  resources:
    requests:
      storage: {{.n}}Gi
